version: '3.4'

x-logging: &default-logging
  options:
    max-size: '10m'
    max-file: '4'
    tag: '{{.ImageName}}|{{.Name}}'
  driver: json-file

services:
  postgres:
    image: 'postgres:12.3'
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - nodanorm-postgres:/var/lib/postgresql/data
    networks:
      - nodanorm_new

volumes:
  nodanorm-postgres:

networks:
  nodanorm_new:
    driver: bridge
